import img from "../components/Assets/images/section4-1.png";
import star from "../components/Assets/icons/Path 223@2x.png";

export const ListOfCups = [
  {
    id: "1",
    img: img,
    name: "ESPRO COFFEE FRENCH PRESS P7",
    price: "$109.95 - $139.95",
    color1: "#221F20",
    color2: "#FFFFFF",
    color3: "#CACCCE",
    color4: "#221F20",
    star1: star,
    star2: star,
    star3: star,
    star4: star,
    star5: star,
    desc: "",
  },
  {
    id: "2",
    img: img,
    name: "ESPRO COFFEE FRENCH PRESS P6",
    price: "$89.95 $99.95",
    color1: "##221F20",
    color2: "##CACCCE",
    star1: star,
    star2: star,
    star3: star,
    star4: star,
    desc: "sale",
    descColor: "Red",
  },
  {
    id: "3",
    img: img,
    name: "ESPRO COFFEE FRENCH PRESS P7",
    price: "$109.95 - $139.95",
    color1: "#221F20",
    color2: "#FFFFFF",
    color3: "#CACCCE",
    color4: "#221F20",
    star1: star,
    star2: star,
    star3: star,
    star4: star,
    star5: star,
    desc: "new",
    descColor: " #043141",
  },
  {
    id: "1",
    img: img,
    name: "BLOOM POUR OVER COFFEE BREWING KIT, 18 OZ",
    price: "$99.95",
    star1: star,
    star2: star,
    star3: star,
    star4: star,
    star5: star,
  },

  {
    id: "5",
    img: img,
    name: "ESPRO ULTRALIGHT COFFEE PRESS P0",
    price: "$109.95 - $139.95",
    color1: "#221F20",
    color2: "#FFFFFF",
    color3: "#CACCCE",
    color4: "#221F20",
    color5: "#285C4D",
    color6: "#02205C",
    star1: star,
    star2: star,
    star3: star,
    star4: star,
    star5: star,
    desc: "back in stock",
    descColor: "lightBlue",
  },
];
